// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"
#include "nvs_flash.h"
#include "nvs.h"
#include "esp_log.h"

extern bool isC;
extern bool ismmHg;
extern float latest_pressure;
extern float latest_temperature;

static char TAG[] = "event";

void save_bool(const char *key, bool value) {
    nvs_handle_t handle;
    esp_err_t err = nvs_open("storage", NVS_READWRITE, &handle);
    if (err == ESP_OK) {
        err = nvs_set_i32(handle, key, value ? 1 : 0);  // bool сохраняем как int
        nvs_commit(handle);
        nvs_close(handle);
		ESP_LOGI(TAG,"Save complete");
    }
}

void ChangeHumi(lv_event_t * e)
{
	ismmHg=!ismmHg;
	save_bool("ismmHg",ismmHg);
    char str2[32];
    if(ismmHg){
        latest_pressure=latest_pressure / 1.33322;
        snprintf(str2, sizeof(str2), "%d", (int)latest_pressure);
        lv_label_set_text(ui_PresConst, "\n mmHg");
    }
    else{
        snprintf(str2, sizeof(str2), "%d", (int)latest_pressure);
        lv_label_set_text(ui_PresConst, "\n      Pha");
    }
    lv_label_set_text(ui_PresArea, str2);
}

void ChangeTemp(lv_event_t * e)
{
	isC=!isC;
	save_bool("isC",isC);
    char str[32];
    if(isC){
        snprintf(str, sizeof(str), "%d°C", (int)latest_temperature);
    }
    else{
        latest_temperature=latest_temperature*1.8+32;
        snprintf(str, sizeof(str), "%d°F", (int)latest_temperature);
    }
    lv_label_set_text(ui_TempArea, str);
}
