// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: 3.5

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VocCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_VocCont);
    lv_obj_set_width(ui_VocCont, 240);
    lv_obj_set_height(ui_VocCont, 106);
    lv_obj_set_x(ui_VocCont, 120);
    lv_obj_set_y(ui_VocCont, 106);
    lv_obj_set_align(ui_VocCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VocCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_VocCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VocCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VocCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VocCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_VocCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_VocCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_VocCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocArae = lv_label_create(ui_VocCont);
    lv_obj_set_width(ui_VocArae, 175);
    lv_obj_set_height(ui_VocArae, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VocArae, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocArae, "1500");
    lv_obj_set_style_text_color(ui_VocArae, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocArae, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VocArae, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VocArae, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocConst = lv_label_create(ui_VocCont);
    lv_obj_set_width(ui_VocConst, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocConst, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VocConst, -90);
    lv_obj_set_y(ui_VocConst, -35);
    lv_obj_set_align(ui_VocConst, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocConst, "VOC");
    lv_obj_add_flag(ui_VocConst, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_VocConst, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocConst, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VocConst, &ui_font_CO2Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocBar = lv_img_create(ui_VocCont);
    lv_img_set_src(ui_VocBar, &ui_img_iaq_bar_png);
    lv_obj_set_width(ui_VocBar, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_VocBar, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_VocBar, 100);
    lv_obj_set_y(ui_VocBar, 0);
    lv_obj_set_align(ui_VocBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VocBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_VocBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_VocBar, 290);

    ui_VocMin = lv_label_create(ui_VocCont);
    lv_obj_set_width(ui_VocMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VocMin, 85);
    lv_obj_set_y(ui_VocMin, 40);
    lv_obj_set_align(ui_VocMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocMin, "0");
    lv_obj_add_flag(ui_VocMin, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_VocMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VocMin, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocMax = lv_label_create(ui_VocCont);
    lv_obj_set_width(ui_VocMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VocMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VocMax, 70);
    lv_obj_set_y(ui_VocMax, -38);
    lv_obj_set_align(ui_VocMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VocMax, "5000");
    lv_obj_add_flag(ui_VocMax, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_VocMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VocMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VocMax, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VocArrow = lv_img_create(ui_VocCont);
    lv_img_set_src(ui_VocArrow, &ui_img_arrow_bar_png);
    lv_obj_set_width(ui_VocArrow, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_VocArrow, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_VocArrow, 79);
    lv_obj_set_y(ui_VocArrow, 27);
    lv_obj_set_align(ui_VocArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VocArrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_VocArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PresCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_PresCont);
    lv_obj_set_width(ui_PresCont, 240);
    lv_obj_set_height(ui_PresCont, 106);
    lv_obj_set_x(ui_PresCont, -120);
    lv_obj_set_y(ui_PresCont, 106);
    lv_obj_set_align(ui_PresCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PresCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PresCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PresCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PresCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PresCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresArea = lv_label_create(ui_PresCont);
    lv_obj_set_width(ui_PresArea, 155);
    lv_obj_set_height(ui_PresArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PresArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresArea, "1015 ");
    lv_obj_add_flag(ui_PresArea, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_PresArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresArea, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresConst = lv_label_create(ui_PresCont);
    lv_obj_set_width(ui_PresConst, 106);
    lv_obj_set_height(ui_PresConst, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresConst, 30);
    lv_obj_set_y(ui_PresConst, 23);
    lv_obj_set_align(ui_PresConst, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PresConst, "\nmmHg");
    lv_obj_add_flag(ui_PresConst, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_PresConst, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresConst, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresConst, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresConst, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresArrow = lv_img_create(ui_PresCont);
    lv_img_set_src(ui_PresArrow, &ui_img_arrow_png);
    lv_obj_set_width(ui_PresArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PresArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PresArrow, 95);
    lv_obj_set_y(ui_PresArrow, 40);
    lv_obj_set_align(ui_PresArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PresArrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_PresArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PresArrow, 290);

    ui_Co2Cont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Co2Cont);
    lv_obj_set_width(ui_Co2Cont, 240);
    lv_obj_set_height(ui_Co2Cont, 106);
    lv_obj_set_x(ui_Co2Cont, 120);
    lv_obj_set_y(ui_Co2Cont, 0);
    lv_obj_set_align(ui_Co2Cont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Co2Cont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Co2Cont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Co2Cont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Co2Cont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Co2Cont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Co2Cont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Co2Cont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Co2Cont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Co2Cont, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Area = lv_label_create(ui_Co2Cont);
    lv_obj_set_width(ui_Co2Area, 175);
    lv_obj_set_height(ui_Co2Area, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Area, 4);
    lv_obj_set_y(ui_Co2Area, 6);
    lv_obj_set_align(ui_Co2Area, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Area, "1500");
    lv_obj_set_style_text_color(ui_Co2Area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Co2Area, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2Area, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Const = lv_label_create(ui_Co2Cont);
    lv_obj_set_width(ui_Co2Const, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Const, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Const, -90);
    lv_obj_set_y(ui_Co2Const, -35);
    lv_obj_set_align(ui_Co2Const, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Const, "CO₂");
    lv_obj_add_flag(ui_Co2Const, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Co2Const, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2Const, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2Const, &ui_font_CO2Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Bar = lv_img_create(ui_Co2Cont);
    lv_img_set_src(ui_Co2Bar, &ui_img_co2_bar_png);
    lv_obj_set_width(ui_Co2Bar, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Co2Bar, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_Co2Bar, 100);
    lv_obj_set_y(ui_Co2Bar, 0);
    lv_obj_set_align(ui_Co2Bar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Co2Bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Co2Bar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Co2Bar, 290);

    ui_Co2Min = lv_label_create(ui_Co2Cont);
    lv_obj_set_width(ui_Co2Min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Min, 77);
    lv_obj_set_y(ui_Co2Min, 41);
    lv_obj_set_align(ui_Co2Min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Min, "350");
    lv_obj_add_flag(ui_Co2Min, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Co2Min, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2Min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2Min, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Max = lv_label_create(ui_Co2Cont);
    lv_obj_set_width(ui_Co2Max, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Max, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Max, 70);
    lv_obj_set_y(ui_Co2Max, -38);
    lv_obj_set_align(ui_Co2Max, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Max, "5000");
    lv_obj_add_flag(ui_Co2Max, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_Co2Max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Co2Max, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Co2Max, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Co2Arrow = lv_img_create(ui_Co2Cont);
    lv_img_set_src(ui_Co2Arrow, &ui_img_arrow_bar_png);
    lv_obj_set_width(ui_Co2Arrow, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_Co2Arrow, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_Co2Arrow, 79);
    lv_obj_set_y(ui_Co2Arrow, 27);
    lv_obj_set_align(ui_Co2Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Co2Arrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_Co2Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumibilityCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_HumibilityCont);
    lv_obj_set_width(ui_HumibilityCont, 240);
    lv_obj_set_height(ui_HumibilityCont, 106);
    lv_obj_set_x(ui_HumibilityCont, -120);
    lv_obj_set_y(ui_HumibilityCont, 0);
    lv_obj_set_align(ui_HumibilityCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumibilityCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HumibilityCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HumibilityCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HumibilityCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HumibilityCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HumibilityCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumibilityCont, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_width(ui_HumibilityCont, 1, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_HumibilityCont, LV_BORDER_SIDE_FULL, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_HumArea = lv_label_create(ui_HumibilityCont);
    lv_obj_set_width(ui_HumArea, 153);
    lv_obj_set_height(ui_HumArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumArea, "64%");
    lv_obj_set_style_text_color(ui_HumArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HumArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumArea, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumArrow = lv_img_create(ui_HumibilityCont);
    lv_img_set_src(ui_HumArrow, &ui_img_arrow_png);
    lv_obj_set_width(ui_HumArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumArrow, 95);
    lv_obj_set_y(ui_HumArrow, 40);
    lv_obj_set_align(ui_HumArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HumArrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_HumArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HumArrow, 290);

    ui_TempCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_TempCont);
    lv_obj_set_width(ui_TempCont, 240);
    lv_obj_set_height(ui_TempCont, 107);
    lv_obj_set_x(ui_TempCont, -120);
    lv_obj_set_y(ui_TempCont, -107);
    lv_obj_set_align(ui_TempCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TempCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TempCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TempCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TempCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempArea = lv_label_create(ui_TempCont);
    lv_obj_set_width(ui_TempArea, 148);
    lv_obj_set_height(ui_TempArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempArea, "15°C");
    lv_obj_set_style_text_color(ui_TempArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TempArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempArea, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempArrow = lv_img_create(ui_TempCont);
    lv_img_set_src(ui_TempArrow, &ui_img_arrow_png);
    lv_obj_set_width(ui_TempArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempArrow, 95);
    lv_obj_set_y(ui_TempArrow, 40);
    lv_obj_set_align(ui_TempArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempArrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_TempArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TempArrow, 290);

    ui_IaqCont = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_IaqCont);
    lv_obj_set_width(ui_IaqCont, 240);
    lv_obj_set_height(ui_IaqCont, 107);
    lv_obj_set_x(ui_IaqCont, 120);
    lv_obj_set_y(ui_IaqCont, -107);
    lv_obj_set_align(ui_IaqCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_IaqCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_IaqCont, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IaqCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_IaqCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_IaqCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_IaqCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_IaqCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_IaqCont, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_IaqCont, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAQConst = lv_label_create(ui_IaqCont);
    lv_obj_set_width(ui_IAQConst, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IAQConst, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IAQConst, -90);
    lv_obj_set_y(ui_IAQConst, -35);
    lv_obj_set_align(ui_IAQConst, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IAQConst, "IAQ");
    lv_obj_add_flag(ui_IAQConst, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_IAQConst, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IAQConst, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IAQConst, &ui_font_CO2Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAQArea = lv_label_create(ui_IaqCont);
    lv_obj_set_width(ui_IAQArea, 175);
    lv_obj_set_height(ui_IAQArea, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IAQArea, 4);
    lv_obj_set_y(ui_IAQArea, 2);
    lv_obj_set_align(ui_IAQArea, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IAQArea, "500");
    lv_obj_set_style_text_color(ui_IAQArea, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IAQArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IAQArea, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IAQArea, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAQMax = lv_label_create(ui_IaqCont);
    lv_obj_set_width(ui_IAQMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IAQMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IAQMax, 75);
    lv_obj_set_y(ui_IAQMax, -38);
    lv_obj_set_align(ui_IAQMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IAQMax, "500");
    lv_obj_add_flag(ui_IAQMax, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_IAQMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IAQMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IAQMax, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAQMin = lv_label_create(ui_IaqCont);
    lv_obj_set_width(ui_IAQMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IAQMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IAQMin, 85);
    lv_obj_set_y(ui_IAQMin, 40);
    lv_obj_set_align(ui_IAQMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IAQMin, "0");
    lv_obj_add_flag(ui_IAQMin, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_set_style_text_color(ui_IAQMin, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IAQMin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IAQMin, &ui_font_Font3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IAQBar = lv_img_create(ui_IaqCont);
    lv_img_set_src(ui_IAQBar, &ui_img_iaq_bar_png);
    lv_obj_set_width(ui_IAQBar, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_IAQBar, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_IAQBar, 100);
    lv_obj_set_y(ui_IAQBar, 0);
    lv_obj_set_align(ui_IAQBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IAQBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_IAQBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IAQBar, 290);

    ui_IAQArrow = lv_img_create(ui_IaqCont);
    lv_img_set_src(ui_IAQArrow, &ui_img_arrow_bar_png);
    lv_obj_set_width(ui_IAQArrow, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_IAQArrow, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_x(ui_IAQArrow, 79);
    lv_obj_set_y(ui_IAQArrow, 27);
    lv_obj_set_align(ui_IAQArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IAQArrow, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_IAQArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
